const swaggerAutogen = require("swagger-autogen");

const outputFile = "./src/swagger_output.json";
const endpointsFiles = ["./src/index.ts"]; //, "./src/entity/User.ts"
const routePath = "./src/routes/*.ts";

const options = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    // bearerAuth: {
    //   type: "http",
    //   scheme: "bearer",
    //   bearerFormat: "JWT",
    // },
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
};

swaggerAutogen()(outputFile, endpointsFiles, routePath);
